# fly.toml app configuration file generated for express-hs123a on 2025-04-23T21:04:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'express-hs123a'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
